# Part A — Foundations (Conceptual)

## 1.	What is NumPy and why is exits ?

## 2.	NumPy vs Python list vs array module ?

| **Feature**                 | **Python List**             | **Array Module**               | **NumPy Array**                                          |
| --------------------------- | --------------------------- | ------------------------------ | -------------------------------------------------------- |
| **Data Type**               | Stores different data types | Stores only the same data type | Stores only the same data type            |       |
| **Speed**                   | Slow                        | Faster than a list             | Fastest                                                  |
| **Memory Usage**            | Uses more memory            | Uses less memory               | Uses very little memory                                  |
| **Mathematical Operations** | No direct support           | Limited support                | Full mathematical support                                |
| **Use**                     | General-purpose programming | Simple numeric data            | Machine Learning, Data Science, and Scientific Computing |


## 3.	Why NumPy is fast?

## 4.	NumPy roles in data Science / ML /DL / Computer vision ?

## 5.	How Panda’s  Scikit-learn, TensorFlow, use NumPy internally ? 

# Part B — Core Topics (from your PDF, fully expanded)

## 6. Installing and Importing NumPy ?

## 7. The ndarray and why NumPy is memory-efficint ?

In [ ]:
ndarray (N-dimensional Array) is the main data structure in NumPy.
It stores elements of the same data type in a single array and supports 1D, 2D, and multi-dimensional arrays.

#### Example :

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


### Why is NumPy Memory-Efficient?

##### NumPy is memory-efficient because:

- It stores data in continuous memory locations.
- It stores only the same data type, reducing memory usage.
- It uses less memory than Python lists.
- It avoids storing extra information for each element.
- It provides fast access to data because of its memory layout.

## 8. Creating arrays (array , arange, linspace, zeros, ones, random.randint ) ?

In [5]:
#Example:

import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
# Example:

import numpy as np

b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Example:

import numpy as py

c = np.linspace(2,20,5)
print(c)

[ 2.   6.5 11.  15.5 20. ]


In [11]:
# Example:

import numpy as np

d = np.zeros(10)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# Example:

import numpy as np

e = np.ones(5)
print(e)

[1. 1. 1. 1. 1.]


In [15]:
# Example:

import numpy as np

a = np.random.randint(1, 10, 5)
print(a)

[4 9 6 2 5]


### 9. Array attributes ( ndim, shape, size, dtype, itemsize ) ?

In [19]:
# Example:

import numpy as np

a = np.array([[1,2],[3,4]])
print(a.ndim)

2


In [26]:
# Example:

import numpy as np

a = np.array([[10, 20], [30, 40]])
print(a.shape)

(2, 2)


In [30]:
# example:

import numpy as np

a = np.array([10, 20,30, 40])
print(a.size)

4


In [31]:
# Example:

import numpy as np

a = np.array([11,22,33,44,55])
print(a.dtype)

int64


In [32]:
# example:

import numpy as py

a = np.array([120,130,140,150,160,170])
print(a.itemsize)

8
